cargo-features = ["edition"]

[package]
name = "cinnamon"
version = "0.1.0"
authors = ["Shelby Doolittle <shelby@shelbyd.com>"]
edition = "2018"

[dependencies]
failure = "*"
structopt = "0.1.0"
structopt-derive = "0.1.0"

[dependencies.nom]
version = "^3.2"
features = ["verbose-errors"]
